"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-28 05:07:56.335693
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generos_musicales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generos_musicales')),
    sa.UniqueConstraint('nombre', name=op.f('uq_generos_musicales_nombre'))
    )
    op.create_table('idiomas',
    sa.Column('codigo', sa.CHAR(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('codigo', name=op.f('pk_idiomas'))
    )
    op.create_table('ips_bloqueadas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ips_bloqueadas')),
    sa.UniqueConstraint('ip', name=op.f('uq_ips_bloqueadas_ip'))
    )
    op.create_index('idx_ips_blocked_until', 'ips_bloqueadas', ['blocked_until'], unique=False)
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perfiles')),
    sa.UniqueConstraint('nombre', name=op.f('uq_perfiles_nombre'))
    )
    op.create_table('regiones',
    sa.Column('codigo', sa.CHAR(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('codigo', name=op.f('pk_regiones'))
    )
    op.create_table('usuarios',
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('artista', 'curador', name='tipo_usuario'), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('foto_path', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], name=op.f('fk_usuarios_perfil_id_perfiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('correo', name=op.f('uq_usuarios_correo'))
    )
    op.create_table('bitacora_eventos',
    sa.Column('autor_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.String(length=64), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], name=op.f('fk_bitacora_eventos_autor_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bitacora_eventos'))
    )
    op.create_index('idx_bitacora_autor', 'bitacora_eventos', ['autor_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_bitacora_entidad', 'bitacora_eventos', ['entidad', 'entidad_id', sa.text('created_at DESC')], unique=False)
    op.create_table('curador_medios',
    sa.Column('curador_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('playlist', 'blog', 'instagram', 'tiktok', 'youtube', 'facebook', 'twitter', 'radio', 'website', 'eventos', 'otro', name='tipo_medio'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('audiencia_estimada', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curador_id'], ['usuarios.id'], name=op.f('fk_curador_medios_curador_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curador_medios'))
    )
    op.create_index(op.f('ix_curador_medios_curador_id'), 'curador_medios', ['curador_id'], unique=False)
    op.create_table('parametros_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor_cifrado', sa.Text(), nullable=True),
    sa.Column('es_secreto', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], name=op.f('fk_parametros_config_updated_by_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parametros_config')),
    sa.UniqueConstraint('clave', name=op.f('uq_parametros_config_clave'))
    )
    op.create_table('sellos_discograficos',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('fk_sellos_discograficos_created_by_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sellos_discograficos')),
    sa.UniqueConstraint('nombre', name=op.f('uq_sellos_discograficos_nombre'))
    )
    op.create_table('solicitudes_curador',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estado_solicitud_curador'), server_default='pendiente', nullable=False),
    sa.Column('notas_revision', sa.Text(), nullable=True),
    sa.Column('revisor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuarios.id'], name=op.f('fk_solicitudes_curador_revisor_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_solicitudes_curador_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitudes_curador'))
    )
    op.create_index('idx_sol_curador_usuario', 'solicitudes_curador', ['usuario_id', 'estado'], unique=False)
    op.create_table('solicitudes_retiro',
    sa.Column('curador_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', 'pagada', name='estado_solicitud_retiro'), server_default='pendiente', nullable=False),
    sa.Column('metodo_pago', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notas_admin', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curador_id'], ['usuarios.id'], name=op.f('fk_solicitudes_retiro_curador_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitudes_retiro'))
    )
    op.create_table('tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('registro', 'reset', 'confirmacion_email', name='tipo_token'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_tokens_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_tokens_token'))
    )
    op.create_index('idx_tokens_expires', 'tokens', ['expires_at'], unique=False, postgresql_where=sa.text('consumed_at IS NULL'))
    op.create_table('usuario_generos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('preferido', 'excluido', name='tipo_preferencia_genero'), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['generos_musicales.id'], name=op.f('fk_usuario_generos_genero_id_generos_musicales'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_generos_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'genero_id', name=op.f('pk_usuario_generos'))
    )
    op.create_table('usuario_preferencias',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('apertura_musical', sa.Integer(), server_default='50', nullable=False),
    sa.Column('acepta_todos_idiomas', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tipo_lanzamientos', sa.Enum('nuevos', 'post', 'ambos', name='tipo_lanzamientos'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('apertura_musical BETWEEN 0 AND 100', name=op.f('ck_usuario_preferencias_apertura_musical_rango')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_preferencias_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('pk_usuario_preferencias'))
    )
    op.create_table('usuario_preferencias_idiomas',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('idioma_codigo', sa.CHAR(length=2), nullable=False),
    sa.ForeignKeyConstraint(['idioma_codigo'], ['idiomas.codigo'], name=op.f('fk_usuario_preferencias_idiomas_idioma_codigo_idiomas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_preferencias_idiomas_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'idioma_codigo', name=op.f('pk_usuario_preferencias_idiomas'))
    )
    op.create_table('usuario_preferencias_regiones',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('region_codigo', sa.CHAR(length=2), nullable=False),
    sa.ForeignKeyConstraint(['region_codigo'], ['regiones.codigo'], name=op.f('fk_usuario_preferencias_regiones_region_codigo_regiones'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_preferencias_regiones_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'region_codigo', name=op.f('pk_usuario_preferencias_regiones'))
    )
    op.create_table('usuario_redes',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('spotify', 'instagram', 'youtube', 'tiktok', 'facebook', 'twitter', 'soundcloud', 'bandcamp', 'website', 'otro', name='tipo_red_social'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_redes_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario_redes'))
    )
    op.create_index(op.f('ix_usuario_redes_usuario_id'), 'usuario_redes', ['usuario_id'], unique=False)
    op.create_table('wallets',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('saldo_creditos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('saldo_pendiente_retiro', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('saldo_creditos >= 0', name=op.f('ck_wallets_saldo_creditos_no_negativo')),
    sa.CheckConstraint('saldo_pendiente_retiro >= 0', name=op.f('ck_wallets_saldo_pendiente_no_negativo')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_wallets_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('pk_wallets'))
    )
    op.create_table('campanas',
    sa.Column('artista_id', sa.UUID(), nullable=False),
    sa.Column('sello_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_audio', sa.String(length=512), nullable=False),
    sa.Column('url_imagen', sa.String(length=512), nullable=True),
    sa.Column('url_material', sa.String(length=512), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'enviada', 'en_revision', 'completada', 'cancelada', name='estado_campana'), server_default='borrador', nullable=False),
    sa.Column('creditos_usados', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['usuarios.id'], name=op.f('fk_campanas_artista_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['genero_id'], ['generos_musicales.id'], name=op.f('fk_campanas_genero_id_generos_musicales'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sello_id'], ['sellos_discograficos.id'], name=op.f('fk_campanas_sello_id_sellos_discograficos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campanas'))
    )
    op.create_index('idx_campanas_artista', 'campanas', ['artista_id', 'estado'], unique=False)
    op.create_index('idx_campanas_estado', 'campanas', ['estado'], unique=False)
    op.create_table('curador_medio_generos',
    sa.Column('medio_id', sa.UUID(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['generos_musicales.id'], name=op.f('fk_curador_medio_generos_genero_id_generos_musicales'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medio_id'], ['curador_medios.id'], name=op.f('fk_curador_medio_generos_medio_id_curador_medios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medio_id', 'genero_id', name=op.f('pk_curador_medio_generos'))
    )
    op.create_table('sello_artistas',
    sa.Column('sello_id', sa.UUID(), nullable=False),
    sa.Column('artista_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.Enum('owner', 'manager', 'artista', name='rol_sello_artista'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['usuarios.id'], name=op.f('fk_sello_artistas_artista_id_usuarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sello_id'], ['sellos_discograficos.id'], name=op.f('fk_sello_artistas_sello_id_sellos_discograficos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sello_id', 'artista_id', name=op.f('pk_sello_artistas'))
    )
    op.create_table('campana_medios',
    sa.Column('campana_id', sa.UUID(), nullable=False),
    sa.Column('medio_id', sa.UUID(), nullable=False),
    sa.Column('curador_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', 'entregada', 'expirada', name='estado_campana_medio'), server_default='pendiente', nullable=False),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creditos_retenidos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas.id'], name=op.f('fk_campana_medios_campana_id_campanas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curador_id'], ['usuarios.id'], name=op.f('fk_campana_medios_curador_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medio_id'], ['curador_medios.id'], name=op.f('fk_campana_medios_medio_id_curador_medios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campana_medios'))
    )
    op.create_index('idx_campana_medios_campana', 'campana_medios', ['campana_id'], unique=False)
    op.create_index('idx_campana_medios_curador', 'campana_medios', ['curador_id', 'estado'], unique=False)
    op.create_index('idx_campana_medios_fecha', 'campana_medios', ['fecha_limite'], unique=False, postgresql_where=sa.text("estado = 'pendiente'"))
    op.create_table('creditos_transacciones',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('compra', 'gasto', 'devolucion', 'retiro', name='tipo_transaccion_credito'), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('referencia_stripe', sa.String(length=255), nullable=True),
    sa.Column('campana_id', sa.UUID(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas.id'], name=op.f('fk_creditos_transacciones_campana_id_campanas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_creditos_transacciones_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creditos_transacciones'))
    )
    op.create_index('idx_creditos_usuario', 'creditos_transacciones', ['usuario_id', sa.text('created_at DESC')], unique=False)
    op.create_table('entregas_contenido',
    sa.Column('campana_medio_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('blog', 'playlist', 'reel', 'link', 'post', name='tipo_entrega'), nullable=False),
    sa.Column('url_entrega', sa.String(length=512), nullable=True),
    sa.Column('contenido_html', sa.Text(), nullable=True),
    sa.Column('puntuacion_autenticidad', sa.Integer(), nullable=True),
    sa.Column('metadatos_escritura', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aprobada_por_artista', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campana_medio_id'], ['campana_medios.id'], name=op.f('fk_entregas_contenido_campana_medio_id_campana_medios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entregas_contenido'))
    )
    op.create_index(op.f('ix_entregas_contenido_campana_medio_id'), 'entregas_contenido', ['campana_medio_id'], unique=False)
    # ### end Alembic commands ###

    # ── Seed de catálogos: idiomas (ISO 639-1) y regiones (ISO 3166-1 alpha-2) ──
    # Se seedean aquí (no en 0002) porque son catálogos de referencia inmutables
    # de los que dependen las preferencias de usuario. Al hacer downgrade, el
    # DROP de las tablas elimina estos datos automáticamente.
    # OJO: usar sa.String (no sa.CHAR) en la tabla del bulk_insert. sa.CHAR sin
    # longitud genera el cast ::CHAR == CHAR(1), que truncaría 'es'→'e'. La
    # columna física sigue siendo CHAR(2) (definida en create_table).
    idiomas_tbl = sa.table(
        "idiomas", sa.column("codigo", sa.String), sa.column("nombre", sa.String)
    )
    op.bulk_insert(
        idiomas_tbl,
        [
            {"codigo": "es", "nombre": "Español"},
            {"codigo": "en", "nombre": "Inglés"},
            {"codigo": "pt", "nombre": "Portugués"},
            {"codigo": "fr", "nombre": "Francés"},
            {"codigo": "it", "nombre": "Italiano"},
            {"codigo": "de", "nombre": "Alemán"},
            {"codigo": "ja", "nombre": "Japonés"},
            {"codigo": "ko", "nombre": "Coreano"},
        ],
    )

    regiones_tbl = sa.table(
        "regiones", sa.column("codigo", sa.String), sa.column("nombre", sa.String)
    )
    op.bulk_insert(
        regiones_tbl,
        [
            {"codigo": "MX", "nombre": "México"},
            {"codigo": "US", "nombre": "Estados Unidos"},
            {"codigo": "ES", "nombre": "España"},
            {"codigo": "AR", "nombre": "Argentina"},
            {"codigo": "CO", "nombre": "Colombia"},
            {"codigo": "CL", "nombre": "Chile"},
            {"codigo": "PE", "nombre": "Perú"},
            {"codigo": "BR", "nombre": "Brasil"},
            {"codigo": "UY", "nombre": "Uruguay"},
            {"codigo": "EC", "nombre": "Ecuador"},
            {"codigo": "GT", "nombre": "Guatemala"},
            {"codigo": "CR", "nombre": "Costa Rica"},
            {"codigo": "DO", "nombre": "República Dominicana"},
            {"codigo": "PR", "nombre": "Puerto Rico"},
            {"codigo": "VE", "nombre": "Venezuela"},
            {"codigo": "GB", "nombre": "Reino Unido"},
            {"codigo": "FR", "nombre": "Francia"},
            {"codigo": "DE", "nombre": "Alemania"},
            {"codigo": "IT", "nombre": "Italia"},
            {"codigo": "CA", "nombre": "Canadá"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entregas_contenido_campana_medio_id'), table_name='entregas_contenido')
    op.drop_table('entregas_contenido')
    op.drop_index('idx_creditos_usuario', table_name='creditos_transacciones')
    op.drop_table('creditos_transacciones')
    op.drop_index('idx_campana_medios_fecha', table_name='campana_medios', postgresql_where=sa.text("estado = 'pendiente'"))
    op.drop_index('idx_campana_medios_curador', table_name='campana_medios')
    op.drop_index('idx_campana_medios_campana', table_name='campana_medios')
    op.drop_table('campana_medios')
    op.drop_table('sello_artistas')
    op.drop_table('curador_medio_generos')
    op.drop_index('idx_campanas_estado', table_name='campanas')
    op.drop_index('idx_campanas_artista', table_name='campanas')
    op.drop_table('campanas')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_usuario_redes_usuario_id'), table_name='usuario_redes')
    op.drop_table('usuario_redes')
    op.drop_table('usuario_preferencias_regiones')
    op.drop_table('usuario_preferencias_idiomas')
    op.drop_table('usuario_preferencias')
    op.drop_table('usuario_generos')
    op.drop_index('idx_tokens_expires', table_name='tokens', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_table('tokens')
    op.drop_table('solicitudes_retiro')
    op.drop_index('idx_sol_curador_usuario', table_name='solicitudes_curador')
    op.drop_table('solicitudes_curador')
    op.drop_table('sellos_discograficos')
    op.drop_table('parametros_config')
    op.drop_index(op.f('ix_curador_medios_curador_id'), table_name='curador_medios')
    op.drop_table('curador_medios')
    op.drop_index('idx_bitacora_entidad', table_name='bitacora_eventos')
    op.drop_index('idx_bitacora_autor', table_name='bitacora_eventos')
    op.drop_table('bitacora_eventos')
    op.drop_table('usuarios')
    op.drop_table('regiones')
    op.drop_table('perfiles')
    op.drop_index('idx_ips_blocked_until', table_name='ips_bloqueadas')
    op.drop_table('ips_bloqueadas')
    op.drop_table('idiomas')
    op.drop_table('generos_musicales')
    # ### end Alembic commands ###

    # Alembic NO elimina los tipos ENUM nativos al hacer drop_table; hay que
    # soltarlos explícitamente o un re-upgrade falla con "type already exists".
    for enum_name in (
        "tipo_usuario",
        "rol_sello_artista",
        "estado_solicitud_curador",
        "tipo_medio",
        "tipo_preferencia_genero",
        "tipo_lanzamientos",
        "tipo_red_social",
        "tipo_transaccion_credito",
        "estado_campana",
        "estado_campana_medio",
        "tipo_entrega",
        "estado_solicitud_retiro",
        "tipo_token",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
